# snow-cicd-lab
snowflake_project:
  target: dev
  outputs:
    dev: &base
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: CICD_ROLE
      warehouse: CICD_WH
      database: ANALYTICS_DEV
      schema: STG_ANALYTICS
      threads: 4

    ci: # utilise par les PR : schema dedie a chaque PR, dans la base DEV
      <<: *base
      database: ANALYTICS_DEV
      schema: "{{ env_var('DBT_SCHEMA', 'CI_LOCAL') }}"

    uat:
      <<: *base
      database: ANALYTICS_UAT

    prod:
      <<: *base
      database: ANALYTICS_PROD