version: 2

models:
  - name: stg_customers
    description: Clients nettoyes
    columns:
      - name: customer_id
        data_tests: [not_null, unique]
      - name: country
        data_tests: [not_null]