repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
rev: v0.6.9 # remplace par la derniere version (pre-commit autoupdate)
hooks:
- id: ruff
- id: ruff-format
- repo: https://github.com/sqlfluff/sqlfluff
rev: 3.2.0
hooks:
- id: sqlfluff-lint
- repo: https://github.com/gitleaks/gitleaks
rev: v8.21.2
hooks:
- id: gitleaks